# -*- coding: utf-8 -*-
"""
H/MIX GALLERY - Track Data (Python version)
tracks.js と同じデータをPythonネイティブ形式で保持します。
generate_music_pages.py から import して使用します。
"""

TRACKS = [

  # ═══════════════════════════════════════════════
  # JAPANESE / WAFUU（和風）— 15 tracks
  # ═══════════════════════════════════════════════

  {
    "id": "n82",
    "slug": "kashishi-no-mai",
    "title": "華志の舞",
    "titleEn": "Dance of Aspiration",
    "mp3": "/music/n/n82.mp3",
    "duration": "4:13",
    "tags": ["japanese", "battle", "epic", "traditional"],
    "mood": ["intense", "dramatic", "powerful", "heroic"],
    "sceneTags": ["samurai battle", "japanese action", "final battle", "warrior dance", "sword fight"],
    "descriptionJa": "三味線と笛が響く、高揚感あふれる和風バトルBGMです。侍の戦い、アクションシーン、壮大な武者の瞬間に最適です。",
    "description": "A high-energy Japanese BGM featuring shamisen and flute. Perfect for samurai battle scenes, action sequences, and epic warrior moments.",
    "category": "japanese"
  },
  {
    "id": "n72",
    "slug": "yoimatsuri-no-kaze",
    "title": "宵祭りの風",
    "titleEn": "Evening Festival Wind",
    "mp3": "/music/n/n72.mp3",
    "duration": "3:39",
    "tags": ["japanese", "peaceful", "festival", "night"],
    "mood": ["calm", "nostalgic", "warm", "gentle"],
    "sceneTags": ["japanese festival", "summer night", "peaceful village", "shrine festival", "fireworks"],
    "descriptionJa": "夏祭りの夜をイメージした、穏やかな和風BGMです。温かい風、遠くの花火、神社の静かな雰囲気を表現しています。",
    "description": "A gentle Japanese BGM evoking a summer festival night. Warm wind, distant fireworks, and peaceful shrine atmosphere.",
    "category": "japanese"
  },
  {
    "id": "n97",
    "slug": "tsukiyo-cho-kimi-wo-omou",
    "title": "月夜蝶～君ヲ想フ～",
    "titleEn": "Moonlit Butterfly",
    "mp3": "/music/n/n97.mp3",
    "duration": "2:13",
    "tags": ["japanese", "sad", "romantic", "night"],
    "mood": ["melancholy", "emotional", "longing", "bittersweet"],
    "sceneTags": ["moonlit night", "sad farewell", "japanese romance", "secret love", "separation"],
    "descriptionJa": "月夜の切ない和風BGMです。恋慕、別れ、月明かりの下の静かな悲しみを表現しています。",
    "description": "A melancholic Japanese BGM for moonlit nights. Evokes longing, separation, and quiet sorrow under the moon.",
    "category": "japanese"
  },
  {
    "id": "n76",
    "slug": "kaiten-dochi",
    "title": "廻天動地",
    "titleEn": "Heaven and Earth Shaking",
    "mp3": "/music/n/n76.mp3",
    "duration": "2:06",
    "tags": ["japanese", "battle", "epic", "dark"],
    "mood": ["dark", "intense", "mysterious", "powerful"],
    "sceneTags": ["final boss", "japanese boss battle", "dark ritual", "last stand", "ominous power"],
    "descriptionJa": "圧倒的な力を持つ和風ボスバトルBGMです。神秘的で荘厳、そして圧倒的。ラスボス戦に最適です。",
    "description": "A powerful Japanese boss battle BGM. Mysterious, solemn, and overwhelming — perfect for final boss encounters.",
    "category": "japanese"
  },
  {
    "id": "n96",
    "slug": "soukoku-no-yoake",
    "title": "創国の夜明け",
    "titleEn": "Dawn of Nation",
    "mp3": "/music/n/n96.mp3",
    "duration": "1:45",
    "tags": ["japanese", "battle", "epic", "action"],
    "mood": ["intense", "dramatic", "powerful", "determined"],
    "sceneTags": ["samurai battle", "dawn of war", "japanese opening", "nation building", "warrior spirit"],
    "descriptionJa": "三味線から始まり、壮大なオーケストラへと発展する緊張感あふれる和風BGMです。国の誕生と武者の魂を表現しています。",
    "description": "A tense, fast-paced Japanese BGM. Opens with shamisen, builds to a grand orchestral finale evoking the birth of a nation.",
    "category": "japanese"
  },
  {
    "id": "n71",
    "slug": "ryoran-enbu",
    "title": "繚乱炎武",
    "titleEn": "Blazing Warrior Dance",
    "mp3": "/music/n/n71.mp3",
    "duration": "3:00",
    "tags": ["japanese", "battle", "epic", "orchestral"],
    "mood": ["dramatic", "powerful", "emotional", "intense"],
    "sceneTags": ["samurai battle", "final battle", "warrior spirit", "japanese epic", "sacrifice"],
    "descriptionJa": "壮大なオーケストラによる和風バトルBGMです。戦場の悲しみ、激しさ、そして武者の魂を描いています。",
    "description": "A grand orchestral Japanese battle BGM. Depicts the sorrow, intensity, and spirit of warriors in combat.",
    "category": "japanese"
  },
  {
    "id": "n103",
    "slug": "kokorozashi-wa-shinanai",
    "title": "志は死なない",
    "titleEn": "The Spirit Never Dies",
    "mp3": "/music/n/n103.mp3",
    "duration": "4:16",
    "tags": ["japanese", "epic", "healing", "orchestral"],
    "mood": ["dramatic", "peaceful", "spiritual", "triumphant"],
    "sceneTags": ["japanese epic", "spring landscape", "samurai spirit", "story ending", "peace after war"],
    "descriptionJa": "尺八とオーケストラによる感動的な和風BGMです。春の美しさと、受け継がれる武者の魂を表現しています。",
    "description": "A dramatic Japanese BGM with shakuhachi and orchestra. Depicts the beauty of spring and the undying spirit of tradition.",
    "category": "japanese"
  },
  {
    "id": "n7",
    "slug": "reiju-ni-idakarete",
    "title": "霊樹に抱かれて",
    "titleEn": "Embraced by the Sacred Tree",
    "mp3": "/music/n/n7.mp3",
    "duration": "1:43",
    "tags": ["japanese", "healing", "fantasy", "spiritual"],
    "mood": ["spiritual", "calm", "mysterious", "ethereal"],
    "sceneTags": ["night shrine", "japanese fantasy", "spirit forest", "healing scene", "sacred tree"],
    "descriptionJa": "神社や精霊の森をイメージした、神秘的な和風ファンタジーBGMです。静かで幻想的な雰囲気が、RPGの神聖な場面に最適です。",
    "description": "A mystical Japanese BGM for shrine and spirit forest scenes. Quiet and ethereal, perfect for fantasy RPG environments.",
    "category": "japanese"
  },
  {
    "id": "n59",
    "slug": "hana-yo-kawa-yo-kono-daichi-yo",
    "title": "花よ川よこの大地よ",
    "titleEn": "Flowers, Rivers, and This Land",
    "mp3": "/music/n/n59.mp3",
    "duration": "3:57",
    "tags": ["japanese", "healing", "epic", "traditional"],
    "mood": ["spiritual", "peaceful", "emotional", "grateful"],
    "sceneTags": ["japanese nature", "sacred land", "village scene", "earth prayer", "harvest festival"],
    "descriptionJa": "大地への感謝と自然の美しさを表現した、穏やかで神秘的な和風BGMです。村や自然の風景シーンに最適です。",
    "description": "A gentle, mystical Japanese BGM expressing gratitude for nature and the land. Perfect for village and nature scenes.",
    "category": "japanese"
  },
  {
    "id": "n93",
    "slug": "shingeki-no-gouryo",
    "title": "進撃の号令",
    "titleEn": "Battle Cry",
    "mp3": "/music/n/n93.mp3",
    "duration": "1:41",
    "tags": ["japanese", "battle", "epic", "action"],
    "mood": ["intense", "powerful", "determined", "urgent"],
    "sceneTags": ["samurai charge", "battle cry", "japanese war", "army march", "warrior charge"],
    "descriptionJa": "激しく緊迫した和風バトルBGMです。突撃の号令、軍勢の行進、戦いの幕開けシーンに最適です。",
    "description": "A fierce and urgent Japanese battle BGM. The call to charge — perfect for army march and battle opening scenes.",
    "category": "japanese"
  },
  {
    "id": "n139",
    "slug": "target-tsukiyo-no-kariudo",
    "title": "Target-月夜の狩人-",
    "titleEn": "Target - Moonlit Hunter",
    "mp3": "/music/n/n139.mp3",
    "duration": "1:23",
    "tags": ["japanese", "battle", "suspense", "night"],
    "mood": ["tense", "focused", "mysterious", "cool"],
    "sceneTags": ["ninja scene", "moonlit assassin", "stealth mission", "night hunter", "samurai thriller"],
    "descriptionJa": "月明かりの下で動く熟練の刺客をイメージした、クールで緊張感ある和風BGMです。忍者やステルスゲームのシーンに最適です。",
    "description": "A cool, tense BGM for a skilled assassin under the moonlight. Perfect for ninja and stealth game scenes.",
    "category": "japanese"
  },
  {
    "id": "n39",
    "slug": "yozakura-koji",
    "title": "夜桜小路",
    "titleEn": "Night Cherry Blossom Lane",
    "mp3": "/music/n/n39.mp3",
    "duration": "1:47",
    "tags": ["japanese", "romantic", "peaceful", "night"],
    "mood": ["nostalgic", "warm", "calm", "romantic"],
    "sceneTags": ["cherry blossom night", "japanese romance", "festival night", "lovers walk", "spring evening"],
    "descriptionJa": "太鼓と弦楽器が織りなす、ロマンチックな和風BGMです。夜桜の下、祭りを遠くに眺めながら歩くような情景を描いています。",
    "description": "A romantic Japanese BGM with taiko drums and strings. Like watching a festival from a distance with someone special.",
    "category": "japanese"
  },
  {
    "id": "n40",
    "slug": "achu-no-shikaku",
    "title": "靄中の刺客",
    "titleEn": "Assassin in the Mist",
    "mp3": "/music/n/n40.mp3",
    "duration": "2:19",
    "tags": ["japanese", "suspense", "battle", "dark"],
    "mood": ["tense", "mysterious", "dark", "focused"],
    "sceneTags": ["ninja assassin", "mist battle", "stealth fight", "samurai suspense", "dark forest"],
    "descriptionJa": "霧の中の刺客をイメージした、緊張感ある和風BGMです。謎めいて危険な雰囲気が、忍者や暗殺者のシーンに最適です。",
    "description": "A tense Japanese BGM for assassin and stealth scenes. Mysterious and dangerous, perfect for ninja encounters.",
    "category": "japanese"
  },
  {
    "id": "n23",
    "slug": "yoru-to-tomo-ni-fukeru",
    "title": "夜と共に耽る",
    "titleEn": "Lost in the Night",
    "mp3": "/music/n/n23.mp3",
    "duration": "1:32",
    "tags": ["japanese", "ambient", "healing", "night"],
    "mood": ["mysterious", "calm", "spiritual", "meditative"],
    "sceneTags": ["night meditation", "japanese ambient", "zen scene", "space ambient", "quiet night"],
    "descriptionJa": "宇宙、瞑想、尺八が融合した、静かな夜の和風アンビエントBGMです。禅の世界観や瞑想シーンに最適です。",
    "description": "A rare ambient piece. Space, meditation, and shakuhachi in a quiet nocturnal Japanese atmosphere.",
    "category": "japanese"
  },
  {
    "id": "n36",
    "slug": "sakusen-kaigi",
    "title": "作戦会議",
    "titleEn": "Strategy Meeting",
    "mp3": "/music/n/n36.mp3",
    "duration": "1:53",
    "tags": ["japanese", "suspense", "epic", "orchestral"],
    "mood": ["tense", "focused", "determined", "serious"],
    "sceneTags": ["war council", "strategy scene", "samurai planning", "battle preparation", "serious meeting"],
    "descriptionJa": "軍議や作戦会議をイメージした、壮大で緊張感あふれる和風BGMです。低音の重厚さとオーケストラの緊張感が場の雰囲気を作ります。",
    "description": "A grand and tense BGM for war councils and strategy scenes. Low bass and orchestral tension build the atmosphere.",
    "category": "japanese"
  },

  # ═══════════════════════════════════════════════
  # HORROR（ホラー）— 10 tracks
  # ═══════════════════════════════════════════════

  {
    "id": "n129",
    "slug": "kagami-no-sekai-wa-nemuranai",
    "title": "鏡の世界は眠らない",
    "titleEn": "The Mirror World Never Sleeps",
    "mp3": "/music/n/n129.mp3",
    "duration": "2:56",
    "tags": ["horror", "mystery", "ambient", "dark"],
    "mood": ["eerie", "dark", "unsettling", "creeping"],
    "sceneTags": ["horror chase", "psychological horror", "mirror world", "creeping dread", "invasion"],
    "descriptionJa": "じわじわと迫りくる恐怖を描いたホラーBGMです。何かが侵食してくる、何かが変わっていく——心理ホラーシーンに最適です。",
    "description": "A slow-building horror BGM. Something is invading, something is changing — perfect for psychological horror scenes.",
    "category": "horror"
  },
  {
    "id": "n80",
    "slug": "satsuriku-machine",
    "title": "殺戮マシン",
    "titleEn": "Slaughter Machine",
    "mp3": "/music/n/n80.mp3",
    "duration": "3:19",
    "tags": ["horror", "battle", "dark", "intense"],
    "mood": ["intense", "dark", "fearful", "chaotic"],
    "sceneTags": ["horror chase", "monster attack", "final horror", "losing sanity", "transformation"],
    "descriptionJa": "理性が徐々に失われていく恐怖を描いたホラーBGMです。ノイズが積み重なり、何かが恐ろしい殺戮マシンへと変貌していきます。",
    "description": "A horror BGM depicting the gradual loss of reason. Noise builds as something terrifying transforms into a killing machine.",
    "category": "horror"
  },
  {
    "id": "n3",
    "slug": "bouryaku-no-ma",
    "title": "謀略の間",
    "titleEn": "Chamber of Conspiracy",
    "mp3": "/music/n/n3.mp3",
    "duration": "2:41",
    "tags": ["horror", "mystery", "suspense", "dark"],
    "mood": ["dark", "tense", "eerie", "ominous"],
    "sceneTags": ["conspiracy scene", "dark chamber", "villain theme", "suspense horror", "secret meeting"],
    "descriptionJa": "陰謀と不安が漂う、暗く謀略的なホラーBGMです。悪役のアジトや、影の密会シーンに最適です。",
    "description": "A dark, conspiratorial BGM for scenes of intrigue and unease. Perfect for villain lairs and shadowy meetings.",
    "category": "horror"
  },
  {
    "id": "n100",
    "slug": "shinen-ni-nozomu",
    "title": "深淵に臨む",
    "titleEn": "Facing the Abyss",
    "mp3": "/music/n/n100.mp3",
    "duration": "2:04",
    "tags": ["horror", "dark", "epic", "intense"],
    "mood": ["dark", "intense", "desperate", "overwhelming"],
    "sceneTags": ["abyss scene", "dark ocean", "horror confrontation", "despair", "facing darkness"],
    "descriptionJa": "渦巻く深淵に向き合う、激しいホラーBGMです。孤独、葛藤、そして圧倒的な闇と戦う様子を描いています。",
    "description": "An intense, swirling horror BGM. Depicts solitude, inner conflict, and struggling against overwhelming darkness.",
    "category": "horror"
  },
  {
    "id": "n132",
    "slug": "chaos-seishin-houkai",
    "title": "chaos-精神崩壊-",
    "titleEn": "Chaos - Mental Collapse",
    "mp3": "/music/n/n132.mp3",
    "duration": "3:11",
    "tags": ["horror", "dark", "ambient", "intense"],
    "mood": ["dark", "chaotic", "fearful", "unstable"],
    "sceneTags": ["mental breakdown", "psychological horror", "chaos scene", "losing mind", "madness"],
    "descriptionJa": "精神崩壊の波を描いたホラーBGMです。心理ホラーや精神崩壊シーンに最適です。",
    "description": "A horror BGM depicting waves of mental collapse. Ideal for psychological horror and breakdown scenes.",
    "category": "horror"
  },
  {
    "id": "n44",
    "slug": "koroshita",
    "title": "殺した",
    "titleEn": "Killed",
    "mp3": "/music/n/n44.mp3",
    "duration": "3:08",
    "tags": ["horror", "dark", "mystery", "gothic"],
    "mood": ["dark", "eerie", "dramatic", "sinister"],
    "sceneTags": ["gothic horror", "dark tango", "murder mystery", "haunted mansion", "dark comedy"],
    "descriptionJa": "不気味なゴシックタンゴ。お化け屋敷や、ダークミステリーの物語に最適です。",
    "description": "A sinister gothic tango. Perfect for haunted mansion scenes and dark mystery narratives.",
    "category": "horror"
  },
  {
    "id": "n98",
    "slug": "tremaine-fujin-no-kiritsu",
    "title": "トレメイン夫人の厳格な規律",
    "titleEn": "Lady Tremaine's Strict Rules",
    "mp3": "/music/n/n98.mp3",
    "duration": "2:25",
    "tags": ["horror", "mystery", "quirky", "gothic"],
    "mood": ["eerie", "dramatic", "dark", "theatrical"],
    "sceneTags": ["gothic horror", "circus horror", "haunted waltz", "dark fairy tale", "villain theme"],
    "descriptionJa": "テルミンが奏でる不気味なサーカスワルツ。ゴシックホラーやダークなおとぎ話に最適です。",
    "description": "A sinister circus waltz with theremin. Eerie and theatrical, perfect for gothic horror and dark fairy tales.",
    "category": "horror"
  },
  {
    "id": "v2",
    "slug": "ningyo-asobi",
    "title": "人形遊び",
    "titleEn": "Doll Play",
    "mp3": "/music/v/v2.mp3",
    "duration": "1:20",
    "tags": ["horror", "mystery", "ambient", "dark"],
    "mood": ["eerie", "dark", "unsettling", "strange"],
    "sceneTags": ["haunted doll", "horror child", "otherworld", "creepy scene", "puppet horror"],
    "descriptionJa": "子供、道化師、そして異世界——短くも不気味なホラー小品です。呪われた人形のシーンに最適です。",
    "description": "A short, unsettling horror piece. Children, clowns, and the otherworldly — perfect for haunted doll scenes.",
    "category": "horror"
  },
  {
    "id": "r1",
    "slug": "shikei-gyoretsu",
    "title": "死刑行列",
    "titleEn": "Death March",
    "mp3": "/music/r/r1.mp3",
    "duration": "3:54",
    "tags": ["horror", "sad", "epic", "dark"],
    "mood": ["dark", "emotional", "solemn", "compassionate"],
    "sceneTags": ["death march", "tragic ending", "funeral scene", "horror sad", "life and death"],
    "descriptionJa": "生と死、そして優しい慈悲をテーマにした、荘厳で深く感動的なBGMです。暗くも美しい、生命の讃歌です。",
    "description": "A solemn and deeply moving BGM about life, death, and gentle compassion. Dark yet beautiful.",
    "category": "horror"
  },
  {
    "id": "n13",
    "slug": "kakusei-no-toki",
    "title": "覚醒の時",
    "titleEn": "Moment of Awakening",
    "mp3": "/music/n/n13.mp3",
    "duration": "1:41",
    "tags": ["horror", "battle", "dark", "epic"],
    "mood": ["dark", "intense", "ominous", "powerful"],
    "sceneTags": ["dark awakening", "villain awakening", "horror boss", "end of the world", "dark power"],
    "descriptionJa": "何か恐ろしいものが目覚める瞬間を描いた、暗く不吉なBGMです。悪役の覚醒やホラーボスシーンに最適です。",
    "description": "A dark and ominous BGM for the awakening of something terrifying. Perfect for villain reveals and horror boss scenes.",
    "category": "horror"
  },

  # ═══════════════════════════════════════════════
  # SAD / EMOTIONAL（悲しい）— 10 tracks
  # ═══════════════════════════════════════════════

  {
    "id": "n74",
    "slug": "moment",
    "title": "Moment",
    "titleEn": "Moment",
    "mp3": "/music/n/n74.mp3",
    "duration": "2:37",
    "tags": ["sad", "japanese", "epic", "emotional"],
    "mood": ["emotional", "melancholy", "dramatic", "bittersweet"],
    "sceneTags": ["sad farewell", "tragic ending", "emotional climax", "bittersweet moment", "anime ending"],
    "descriptionJa": "人の魂が咲き、そして散る様を描いた、切なくも激しいBGMです。アニメのエンディングや感動的なクライマックスシーンに最適です。",
    "description": "A bittersweet and intense BGM. Depicts the blooming and scattering of human spirit — like a flower that lives and dies beautifully.",
    "category": "sad"
  },
  {
    "id": "n75",
    "slug": "moment-orgel",
    "title": "Moment～オルゴールVer～",
    "titleEn": "Moment - Music Box Version",
    "mp3": "/music/n/n75.mp3",
    "duration": "2:49",
    "tags": ["sad", "ambient", "healing", "gentle"],
    "mood": ["melancholy", "gentle", "nostalgic", "tender"],
    "sceneTags": ["sad memory", "music box scene", "gentle farewell", "childhood memory", "quiet emotion"],
    "descriptionJa": "Momentのオルゴールバージョン。優しく懐かしく、記憶のシーンや静かな別れのシーンに最適です。",
    "description": "The music box version of Moment. Gentle and nostalgic, perfect for memory scenes and quiet farewells.",
    "category": "sad"
  },
  {
    "id": "n95",
    "slug": "soukoku",
    "title": "蒼刻～そうこく～",
    "titleEn": "Blue Engraving",
    "mp3": "/music/n/n95.mp3",
    "duration": "1:29",
    "tags": ["sad", "epic", "dramatic", "piano"],
    "mood": ["emotional", "dramatic", "intense", "passionate"],
    "sceneTags": ["emotional climax", "sad battle", "flame of life", "dramatic ending", "burning spirit"],
    "descriptionJa": "切ないピアノから始まり、劇的に盛り上がるBGMです。命の炎が燃え尽きる前に輝くような、情熱的な一曲です。",
    "description": "Opens with melancholic piano, then builds dramatically. Like the flame of life burning brightly before fading.",
    "category": "sad"
  },
  {
    "id": "n123",
    "slug": "itsuka-no-daichi-e",
    "title": "いつかの大地へ",
    "titleEn": "To the Land of Someday",
    "mp3": "/music/n/n123.mp3",
    "duration": "3:39",
    "tags": ["sad", "epic", "japanese", "orchestral"],
    "mood": ["emotional", "melancholy", "dramatic", "longing"],
    "sceneTags": ["sad farewell", "epic journey", "emotional ending", "erhu solo", "vast landscape"],
    "descriptionJa": "二胡の演奏をフィーチャーした、壮大で哀愁漂うテーマ曲です。別れや広大な風景を旅する感動的なBGMです。",
    "description": "A grand and sorrowful theme featuring erhu performance. An epic emotional journey BGM for farewells and vast landscapes.",
    "category": "sad"
  },
  {
    "id": "n145",
    "slug": "hyousetsu-no-shinrin",
    "title": "氷雪の森林",
    "titleEn": "Frozen Forest",
    "mp3": "/music/n/n145.mp3",
    "duration": "2:43",
    "tags": ["sad", "healing", "ambient", "fantasy"],
    "mood": ["mysterious", "peaceful", "melancholy", "ethereal"],
    "sceneTags": ["frozen forest", "winter scene", "mystical nature", "silent snow", "ice world"],
    "descriptionJa": "氷の森に差し込む光をイメージした、神秘的なBGMです。静寂、謎、そして幻想的な美しさを表現しています。",
    "description": "A mystical BGM evoking light filtering through an ice forest. Silence, mystery, and ethereal beauty.",
    "category": "sad"
  },
  {
    "id": "n130",
    "slug": "taiju-sono-tabi-no-owari-ni",
    "title": "大樹-その旅の終わりに-",
    "titleEn": "The Great Tree - At Journey's End",
    "mp3": "/music/n/n130.mp3",
    "duration": "2:55",
    "tags": ["sad", "healing", "epic", "spiritual"],
    "mood": ["emotional", "peaceful", "spiritual", "accepting"],
    "sceneTags": ["journey ending", "life and death", "great tree", "final rest", "cycle of life"],
    "descriptionJa": "旅の終わりに、すべての命を優しく抱きとめる大樹をテーマにしたBGMです。生と死の循環を描いています。",
    "description": "A BGM about the great tree that gently embraces all life at its end. Themed around the cycle of life and death.",
    "category": "sad"
  },
  {
    "id": "n70",
    "slug": "innocent",
    "title": "イノセント",
    "titleEn": "Innocent",
    "mp3": "/music/n/n70.mp3",
    "duration": "1:28",
    "tags": ["sad", "healing", "peaceful", "piano"],
    "mood": ["gentle", "melancholy", "emotional", "pure"],
    "sceneTags": ["innocent child", "gentle sadness", "piano solo", "tender moment", "pure emotion"],
    "descriptionJa": "ピアニスト・関牧子による、繊細で切ないピアノ小品です。純粋で深く心に響く、感動的な一曲です。",
    "description": "A tender and melancholic piano piece. Arranged and performed by pianist Makiko Seki. Pure and deeply moving.",
    "category": "sad"
  },
  {
    "id": "n135",
    "slug": "kamigoto-no-izumi",
    "title": "神言の泉",
    "titleEn": "Spring of Divine Words",
    "mp3": "/music/n/n135.mp3",
    "duration": "2:56",
    "tags": ["sad", "healing", "ambient", "japanese"],
    "mood": ["spiritual", "mysterious", "gentle", "sacred"],
    "sceneTags": ["divine spring", "female vocal", "mystical scene", "prayer scene", "sacred water"],
    "descriptionJa": "ハープと女性ボーカルによる、静かで神聖なBGMです。神秘的で聖なる雰囲気が、祈りや神聖な場面に最適です。",
    "description": "A quiet harp and female vocal piece. Mystical and sacred, perfect for divine or spiritual scenes.",
    "category": "sad"
  },
  {
    "id": "c1",
    "slug": "sennen-no-tsuioku",
    "title": "千年の追憶",
    "titleEn": "A Thousand Years of Memory",
    "mp3": "/music/c/c1.mp3",
    "duration": "4:15",
    "tags": ["sad", "epic", "ambient", "orchestral"],
    "mood": ["nostalgic", "melancholy", "solemn", "timeless"],
    "sceneTags": ["ancient memory", "thousand years", "glory and loss", "epic ending", "timeless sorrow"],
    "descriptionJa": "栄光、過去、そして千年にわたる静かな孤独を表現した、安定した哀愁あふれるBGMです。",
    "description": "A steady, melancholic BGM evoking glory, the past, and a quiet loneliness that spans a thousand years.",
    "category": "sad"
  },
  {
    "id": "n92",
    "slug": "aoi-tsuki",
    "title": "蒼い月",
    "titleEn": "Blue Moon",
    "mp3": "/music/n/n92.mp3",
    "duration": "2:16",
    "tags": ["sad", "healing", "ambient", "guitar"],
    "mood": ["melancholy", "gentle", "nostalgic", "lonely"],
    "sceneTags": ["blue moon", "sad night", "guitar solo", "lonely scene", "quiet sorrow"],
    "descriptionJa": "蒼い月の下で奏でられる、切ないギター小品です。静かで内省的な、孤独な夜のシーンに最適です。",
    "description": "A melancholic guitar piece under a blue moon. Quiet and introspective, perfect for lonely night scenes.",
    "category": "sad"
  },

  # ═══════════════════════════════════════════════
  # HEALING / AMBIENT（癒し）— 8 tracks
  # ═══════════════════════════════════════════════

  {
    "id": "c8",
    "slug": "mori-no-yurikago",
    "title": "森のゆりかご",
    "titleEn": "Forest Cradle",
    "mp3": "/music/c/c8.mp3",
    "duration": "4:04",
    "tags": ["healing", "ambient", "fantasy", "nature"],
    "mood": ["peaceful", "calm", "spiritual", "gentle"],
    "sceneTags": ["forest healing", "nature ambient", "fantasy forest", "relaxation", "forest bathing"],
    "descriptionJa": "森林浴とリラクゼーションをテーマにした、穏やかなアンビエントBGMです。自然のシーンや瞑想に最適です。",
    "description": "A forest bathing and relaxation BGM. Gentle, peaceful, and perfect for nature scenes and meditation.",
    "category": "healing"
  },
  {
    "id": "n31",
    "slug": "seirei-no-machi",
    "title": "精霊の街",
    "titleEn": "Spirit Town",
    "mp3": "/music/n/n31.mp3",
    "duration": "3:05",
    "tags": ["healing", "fantasy", "ambient", "spiritual"],
    "mood": ["mysterious", "peaceful", "spiritual", "warm"],
    "sceneTags": ["spirit town", "fantasy village", "waterside light", "forest town", "RPG town"],
    "descriptionJa": "森の街や水辺の光をイメージした、神秘的な癒しBGMです。精霊が宿るRPGの街シーンに最適です。",
    "description": "A mystical healing BGM for forest towns and waterside scenes. Spiritual and serene, perfect for RPG towns.",
    "category": "healing"
  },
  {
    "id": "n120",
    "slug": "bokyo-no-oka",
    "title": "望郷の丘",
    "titleEn": "Hill of Longing",
    "mp3": "/music/n/n120.mp3",
    "duration": "4:23",
    "tags": ["healing", "peaceful", "epic", "nature"],
    "mood": ["nostalgic", "peaceful", "emotional", "warm"],
    "sceneTags": ["hometown scene", "four seasons", "gentle wind", "peaceful landscape", "longing for home"],
    "descriptionJa": "四季を通じた故郷の美しさを表現した、明るく輝くBGMです。温かく懐かしい気持ちになれる一曲です。",
    "description": "A bright, sparkling BGM evoking the beauty of a hometown through the four seasons. Warm and nostalgic.",
    "category": "healing"
  },
  {
    "id": "n46",
    "slug": "dear-childhood-friend",
    "title": "Dear Childhood Friend",
    "titleEn": "Dear Childhood Friend",
    "mp3": "/music/n/n46.mp3",
    "duration": "3:06",
    "tags": ["healing", "japanese", "peaceful", "nostalgic"],
    "mood": ["nostalgic", "warm", "calm", "tender"],
    "sceneTags": ["childhood memory", "rural landscape", "summer festival", "nostalgia", "old friend"],
    "descriptionJa": "田舎の風景と幼い夏をイメージした、懐かしい和風BGMです。温かく心に染みる一曲です。",
    "description": "A nostalgic Japanese BGM evoking rural landscapes and childhood summers. Warm and heartfelt.",
    "category": "healing"
  },
  {
    "id": "c2",
    "slug": "hidokei-no-oka",
    "title": "日時計の丘",
    "titleEn": "Sundial Hill",
    "mp3": "/music/c/c2.mp3",
    "duration": "2:11",
    "tags": ["healing", "peaceful", "ambient", "light"],
    "mood": ["warm", "peaceful", "nostalgic", "bright"],
    "sceneTags": ["children playing", "afternoon scene", "nature walk", "peaceful village", "sunny day"],
    "descriptionJa": "午後の陽光の中で子供たちが自然の中で遊ぶ様子を描いた、温かく穏やかなBGMです。",
    "description": "A warm and peaceful BGM depicting children playing in nature as the afternoon sun shines.",
    "category": "healing"
  },
  {
    "id": "c7",
    "slug": "hoshijaku-no-sanpomichi",
    "title": "星寂の散歩道",
    "titleEn": "Starlit Promenade",
    "mp3": "/music/c/c7.mp3",
    "duration": "4:09",
    "tags": ["healing", "ambient", "peaceful", "night"],
    "mood": ["calm", "peaceful", "nostalgic", "serene"],
    "sceneTags": ["starlit walk", "night relaxation", "stargazing", "peaceful night", "evening stroll"],
    "descriptionJa": "星空の下の静かな夜の散歩をイメージした、リラクゼーションBGMです。睡眠音楽や星空観察のシーンに最適です。",
    "description": "A starlit relaxation BGM for quiet evening walks and stargazing scenes. Perfect for sleep music and relaxation.",
    "category": "healing"
  },
  {
    "id": "n118",
    "slug": "horumalin-to-taiji",
    "title": "ホルマリンと胎児",
    "titleEn": "Formalin and the Fetus",
    "mp3": "/music/n/n118.mp3",
    "duration": "1:50",
    "tags": ["healing", "ambient", "peaceful", "gentle"],
    "mood": ["peaceful", "gentle", "spiritual", "warm"],
    "sceneTags": ["womb scene", "gentle ambient", "birth scene", "peaceful meditation", "safe place"],
    "descriptionJa": "胎内のような、穏やかで包み込まれるようなアンビエントBGMです。瞑想や安らぎのシーンに最適です。",
    "description": "A calm, womb-like BGM. Serene and enveloping, like being held in gentle warmth. Perfect for meditation.",
    "category": "healing"
  },
  {
    "id": "n33",
    "slug": "yuukyu-no-kizuna",
    "title": "悠久の絆",
    "titleEn": "Eternal Bond",
    "mp3": "/music/n/n33.mp3",
    "duration": "2:11",
    "tags": ["healing", "sad", "peaceful", "strings"],
    "mood": ["gentle", "emotional", "nostalgic", "tender"],
    "sceneTags": ["eternal bond", "gentle farewell", "piano solo", "quiet emotion", "lasting friendship"],
    "descriptionJa": "弦楽器による、静かで深く心に響くBGMです。感動的な別れや、永遠の絆を描くシーンに最適です。",
    "description": "A gentle string version of One Believes. Quiet and deeply moving, perfect for emotional farewell scenes.",
    "category": "healing"
  },

  # ═══════════════════════════════════════════════
  # BATTLE / RPG（バトル・RPG）— 7 tracks
  # ═══════════════════════════════════════════════

  {
    "id": "n144",
    "slug": "karyu-no-doukutsu",
    "title": "火竜の洞窟",
    "titleEn": "Fire Dragon's Cave",
    "mp3": "/music/n/n144.mp3",
    "duration": "2:09",
    "tags": ["battle", "fantasy", "epic", "dungeon"],
    "mood": ["intense", "dramatic", "powerful", "dangerous"],
    "sceneTags": ["dragon cave", "RPG dungeon", "fire dungeon", "boss battle", "dragon fight"],
    "descriptionJa": "火竜の巣窟をイメージした、燃え盛るダンジョンBGMです。RPGのダンジョンやボスバトルシーンに最適です。",
    "description": "A blazing dungeon BGM evoking a fire dragon lair. Perfect for RPG dungeon and boss battle scenes.",
    "category": "battle"
  },
  {
    "id": "n147",
    "slug": "daichi-wo-yurugasu-houkou",
    "title": "大地を揺るがす咆哮",
    "titleEn": "Roar That Shakes the Earth",
    "mp3": "/music/n/n147.mp3",
    "duration": "2:57",
    "tags": ["battle", "epic", "fantasy", "orchestral"],
    "mood": ["intense", "powerful", "dramatic", "overwhelming"],
    "sceneTags": ["final boss", "boss battle", "RPG climax", "earth shaking", "giant enemy"],
    "descriptionJa": "大地を揺るがすほどの咆哮をイメージした、圧倒的なボスバトルBGMです。RPGのラスボス戦に最適です。",
    "description": "An earth-shaking boss battle BGM. Massive scale and intensity — perfect for final boss encounters in RPGs.",
    "category": "battle"
  },
  {
    "id": "n28",
    "slug": "hisho",
    "title": "飛翔",
    "titleEn": "Soaring",
    "mp3": "/music/n/n28.mp3",
    "duration": "4:20",
    "tags": ["battle", "epic", "fantasy", "orchestral"],
    "mood": ["powerful", "dramatic", "intense", "heroic"],
    "sceneTags": ["RPG battle", "heroic battle", "soaring hero", "epic fight", "climax battle"],
    "descriptionJa": "大胆に飛翔するような、英雄的なオーケストラバトルBGMです。RPGのクライマックスバトルシーンに最適です。",
    "description": "A heroic orchestral battle BGM. Bold and soaring, perfect for climactic RPG battle scenes.",
    "category": "battle"
  },
  {
    "id": "n62",
    "slug": "sougen-wo-yuku",
    "title": "草原をゆく",
    "titleEn": "Crossing the Grasslands",
    "mp3": "/music/n/n62.mp3",
    "duration": "2:02",
    "tags": ["battle", "fantasy", "epic", "adventure"],
    "mood": ["adventurous", "peaceful", "dramatic", "exciting"],
    "sceneTags": ["RPG field", "grassland adventure", "overworld theme", "open world", "exploration"],
    "descriptionJa": "草原を旅するRPGのフィールドBGMです。冒険心をかき立てる、オープンワールドの探索シーンに最適です。",
    "description": "An RPG overworld BGM for grassland exploration. Adventurous and exciting, perfect for open-world scenes.",
    "category": "battle"
  },
  {
    "id": "n65",
    "slug": "sajin-no-josai",
    "title": "砂塵の城塞",
    "titleEn": "Fortress of Dust",
    "mp3": "/music/n/n65.mp3",
    "duration": "2:01",
    "tags": ["battle", "epic", "fantasy", "intense"],
    "mood": ["intense", "dramatic", "powerful", "sharp"],
    "sceneTags": ["fortress battle", "RPG battle", "northern epic", "dramatic fight", "castle siege"],
    "descriptionJa": "激しく劇的なバトルBGMです。北方風の壮大なクライマックスへと盛り上がる、城塞攻略シーンに最適です。",
    "description": "A sharp, dramatic battle BGM. Opens intensely and builds to a grand northern-style climax.",
    "category": "battle"
  },
  {
    "id": "n136",
    "slug": "seirei-mai",
    "title": "精霊舞い",
    "titleEn": "Spirit Dance",
    "mp3": "/music/n/n136.mp3",
    "duration": "3:41",
    "tags": ["battle", "fantasy", "japanese", "spiritual"],
    "mood": ["intense", "spiritual", "dramatic", "light"],
    "sceneTags": ["spirit battle", "fantasy battle", "spirit dance", "RPG boss", "elemental fight"],
    "descriptionJa": "精霊の戦いの舞をイメージした、軽やかで激しいバトルBGMです。ファンタジー世界の精霊たちの戦いを描いています。",
    "description": "A spirit battle dance BGM. Light yet intense — imagining the war dance of spirits in a fantasy world.",
    "category": "battle"
  },
  {
    "id": "n15",
    "slug": "eikyuu-no-rinne",
    "title": "永久の輪廻",
    "titleEn": "Eternal Reincarnation",
    "mp3": "/music/n/n15.mp3",
    "duration": "2:39",
    "tags": ["battle", "horror", "epic", "dark"],
    "mood": ["dark", "intense", "mysterious", "ominous"],
    "sceneTags": ["final boss", "dark ritual", "RPG final battle", "eternal cycle", "dark power"],
    "descriptionJa": "永遠の輪廻と宗教的な儀式を描いた、神秘的で激しいBGMです。ダークなラスボス戦に最適です。",
    "description": "A mysterious and intense BGM depicting eternal cycles and religious ritual. Perfect for dark final boss scenes.",
    "category": "battle"
  }

]
